apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: main-rules
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: monitoring
spec:
  groups:
    - name: main.rules
      rules:
      - alert: HIGH CPU LOAD
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) *100) >50
        for: 2m
        labels:
          severity: warning
          namespace: monitoring
        annotations:
          description: "CPU LOAD {{ $value}} {{$labels.instance}}" 
          summary: "HOST CPU LOAD HIGH"
      - alert: K8s POD CRASH
        expr: kube_pod_container_status_restart_total > 5
        for: 0m
        labels:
          severity: critical
          namespace: monitoring
        annotations:
          description: "Pod is Crashlooping {{$labels.pod}} Value = {{ $value }}" 
          summary: "K8s pod crash loop"